export const funFacts = [
  "Michael Jordan’s favorite pre-game snack was graham crackers and applesauce, and hardly ever played a game without first eating it.",
  "Paul Westphal, Suns’ shooting guard, could make 20 shots in a row from the same spot without ever moving, not even for rebounds. He made a bit of money this way off of bets.",
  "Hakeem Olajuwan would play games while fasting for Ramadan.",
  "Walt Bellamy holds the record for most games played in a season with 88.",
  "Kobe Bryant asked for a trade off of the Lakers in 2006.",
  "Danny Ainge was all-state in football, baseball, and basketball in high school, and was even drafted by the Toronto Blue Jays in addition to the Boston Celtics.",
  "Wilt Chamberlain could out-bench Arnold Schwarzenegger.",
  "Shaquille O’Neal’s college coach Dale Brown discovered Shaq at a German military base as a 13 year old.",
  "Dennis Rodman would study how many times the ball spun in the air after his teammates shot it, leading him to be an even better rebounder.",
  "Hakeem Olajuwan is 1st in career blocks and 8th in career steals",
  "Bismack Biyombo holds the record for 2nd most rebounds in a playoff game in NBA history with 26 along with Wilt",
  "Andrew Bynum holds the record for most blocks in a playoff game with 10",
  "3 players in the top 5 in most minutes played in a playoff game, Kirk Hinrich, John Salmons and Derrick Rose, were all coached by Tom Thibodeau it was Vinny Del Negro for half of them",
  "There have only ever been 2 Christmas Eve games in NBA History",
  "The last time a team from neither Texas or California has won in the finals representing the Western Conference was 1977, when the Portland Trailblazers won it all. it was the Sonics in ‘79",
  "Bison Dele, formerly of the Chicago Bulls, was mysteriously murdered on the island of Tahiti in 2002, presumably by his brother",
  "Dennis Rodman once illegally married himself",
  "Jack Sikma is usually not credited as being the first NBA player to popularize the stepback, but he was, it just wasn’t from range",
  "Kevin Durant couldn’t complete a single bench press rep of 185 pounds in the NBA combine.",
  "Oliver Miller was the heaviest player in NBA history at about 375 pounds.",
  "6’8 forward Popeye Jones completed his 10 year career without dunking once. he dunked once, apparently.",
  "Gerald Green only has 9 fingers.",
  "Derrick Coleman is credited as being the only player to ever dunk on Shaquille O’Neal, the source being Shaq himself.",
  "Darryl Dawkins and Shaq are tied for the record of most backboards broken with 2 a piece",
  "David Robinson is nicknamed “The Admiral” because he was withheld from the Navy for being too tall. He then joined the Spurs as the oldest ROTY ever, leading the young Spurs to the conference finals after winning just 21 games the year prior.",
  "Former NBA player and Kobe Bryant’s dad Joe Bryant actually DID name Kobe after the Japanese steak.",
  "Earl Manigault is considered by many including Kareem Abdul-Jabbar to be the most talented basketball player ever despite never playing in the NBA.",
  "Pete Maravich said in an interview when he was 26 that he \"didn't want to play in the NBA for 10 years, then die of a heart attack at 40.” He proceeded to have a 10-year NBA career, and then die of a heart attack at 40.",
  "Tim Duncan only turned to basketball after Hurricane Hugo destroyed his local swimming pool, and his fear of sharks kept him out of the ocean.",
  "Michael Jordan was fined $5,000 by the NBA for each game he wore Air Jordans",
  "The New Orleans Hornets played 6 months of a season in OKC as the Oklahoma City Hornets in 2006",
  "Bonus fact: the Oklahoma City Hornets wore special Valentines Day jerseys for one game in the ‘05-‘06 NBA season. It is widely considered by collectors to be the rarest jersey to collect.",
  "Kobe Bryant’s parents had to co-sign his first NBA contract because he was only 17 at the time.",
  "Manute Bol paid 80 cows for his wife.",
  "Latrell Sprewell never played in the NBA again after turning down a $21 million contract because he claimed he couldn’t feed his family with it.",
  "Randy Foye’s internal organs are mirrored",
  'When a 7ft NBA player named Reggie Harding attempted to rob a Detroit gas station with a mask, the attendant said "I know it\'s you, Reggie.", to which he replied "No, man, it ain\'t me". Nice.',
  "Until 1966, the NBA had Territorial Draft Picks. A team could forgo its first round pick and take any player within 50 miles of its location. They included Wilt Chamberlain and Oscar Robertson. This also happened in 2008 when David Stern rigged the draft for Derrick Rose and the Chicago Bulls.",
  "In 1948, before the NBA had any black players, the Harlem Globetrotters beat the NBA Champion Lakers in a straight up game.",
  'Pat Riley, trademarked the word "Three-Peat" in 1988. When the Chicago Bulls won three straight championships in the 1990s, he was paid $300,000 dollars in royalties.',
  "Wilt Chamberlain has had 32 60 point games, the next closest being Kobe Bryant with 6.",
  "Tim Duncan loves Dungeons and Dragons so much that he wanted to be called Merlin when he joined the NBA.",
  "The 2000 NBA draft, considered to be one of the worst in history, was the only draft that produced an average number of wins below replacement level. In other words, the 2000 draft actually made the NBA less talented.",
  "The reason NBA teams have the white home jersey rule mainly due to the fact in the early days away teams didn't have laundry facilities so they would wear darker clothes to hide dirt.",
  "Alex English led the NBA in points for the entire duration of the 1980’s",
  "Tim Hardaway is credited with creating the modern NBA crossover",
  "Phil Jackson believes the definition of a contender is when a team hits 40 wins before 20 losses.",
];
